"""add fetch_state table

Revision ID: 0c438040e6c0
Revises: 3529f4d278bd
Create Date: 2026-07-03 00:56:05.394672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c438040e6c0'
down_revision: Union[str, None] = '3529f4d278bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_state',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fetch_state')
    # ### end Alembic commands ###
