"""initial schema

Revision ID: 3529f4d278bd
Revises: 
Create Date: 2026-07-03 00:41:28.321243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3529f4d278bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('CVE', 'KEV', 'GHSA', 'GITHUB_POC', 'ATTACK', 'CAPEC', name='findingsource', native_enum=False, length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('raw_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_findings_source_external_id')
    )
    op.create_index(op.f('ix_findings_external_id'), 'findings', ['external_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('notify_email', sa.String(length=255), nullable=True),
    sa.Column('notify_frequency', sa.String(length=20), nullable=False),
    sa.Column('cvss_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('cvss_allowed_attack_vectors', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'finding_id', name='uq_notification_user_finding')
    )
    op.create_index(op.f('ix_notifications_sent_finding_id'), 'notifications_sent', ['finding_id'], unique=False)
    op.create_index(op.f('ix_notifications_sent_user_id'), 'notifications_sent', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by_user_id', name='uq_tags_name_owner')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('tag_attack_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('attack_technique_id', sa.String(length=20), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'attack_technique_id', 'created_by_user_id', name='uq_tag_technique_owner')
    )
    op.create_index(op.f('ix_tag_attack_techniques_tag_id'), 'tag_attack_techniques', ['tag_id'], unique=False)
    op.create_table('tag_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'keyword', 'created_by_user_id', name='uq_tag_keyword_owner')
    )
    op.create_index(op.f('ix_tag_keywords_tag_id'), 'tag_keywords', ['tag_id'], unique=False)
    op.create_table('watchlist_tags',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'tag_id')
    )
    op.create_table('finding_tag_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('matched_keyword_id', sa.Integer(), nullable=True),
    sa.Column('matched_technique_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_keyword_id'], ['tag_keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_technique_id'], ['tag_attack_techniques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'tag_id', 'matched_keyword_id', 'matched_technique_id', name='uq_finding_tag_match')
    )
    op.create_index(op.f('ix_finding_tag_matches_finding_id'), 'finding_tag_matches', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_tag_matches_tag_id'), 'finding_tag_matches', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_tag_matches_tag_id'), table_name='finding_tag_matches')
    op.drop_index(op.f('ix_finding_tag_matches_finding_id'), table_name='finding_tag_matches')
    op.drop_table('finding_tag_matches')
    op.drop_table('watchlist_tags')
    op.drop_index(op.f('ix_tag_keywords_tag_id'), table_name='tag_keywords')
    op.drop_table('tag_keywords')
    op.drop_index(op.f('ix_tag_attack_techniques_tag_id'), table_name='tag_attack_techniques')
    op.drop_table('tag_attack_techniques')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_notifications_sent_user_id'), table_name='notifications_sent')
    op.drop_index(op.f('ix_notifications_sent_finding_id'), table_name='notifications_sent')
    op.drop_table('notifications_sent')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_findings_external_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
